#!/bin/bash

DOTFILES=$(pwd)
echo "=> dotfiles dir: $DOTFILES"

mkdir -p ~/.vim/autoload
mkdir -p ~/.config/nvim
mkdir -p ~/.zsh/modules

ln -sfv "$DOTFILES/alacritty.yml" ~/.alacritty.yml
ln -sfv "$DOTFILES/gitconfig" ~/.gitconfig
ln -sfv "$DOTFILES/gitignore_global" ~/.gitignore_global
ln -sfv "$DOTFILES/vimrc" ~/.vimrc
ln -sfv "$DOTFILES/tmux.conf" ~/.tmux.conf
ln -sfv "$DOTFILES/zshrc" ~/.zshrc
ln -sfv "$DOTFILES/zprofile" ~/.zprofile
ln -sfv "$DOTFILES/.config/nvim/init.vim" ~/.config/nvim
ln -sfv "$DOTFILES/.config/nvim/coc-settings.json" ~/.config/nvim/coc-settings.json

if [ "$(uname -s)" = 'Darwin' ]; then

  [ -z "$(which brew)" ] &&
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  brew analytics off

  echo "=> Updating homebrew"

  brew install bat
  brew install cmake
  brew install coreutils
  brew install fd
  brew install git
  brew install htop
  brew install neovim
  brew install node
  brew install python
  brew install reattach-to-user-namespace
  brew install ripgrep
  brew install tmux
  brew install tree
  brew install vim
  brew install zsh

  brew install --cask alacritty
  brew install --cask visual-studio-code
  brew install --cask telegram
  brew install --cask spectacle

else
  echo "=> linux"
fi

echo "=> Install tmux tpm"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux source-file ~/.tmux.conf

git clone https://github.com/rupa/z.git ~/.zsh/modules
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/modules
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/modules


curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall

