#!/bin/bash

DOTFILES=$(pwd)
echo "=> dotfiles dir: $DOTFILES"

mkdir -p ~/.config/fish
mkdir -p ~/.vim/autoload
mkdir -p ~/.config/nvim

ln -sfv "$DOTFILES/.config/fish/config.fish" ~/.config/fish/config.fish
ln -sfv "$DOTFILES/.config/fish/functions/" ~/.config/fish
ln -sfv "$DOTFILES/alacritty.yml" ~/.alacritty.yml
ln -sfv "$DOTFILES/gitconfig" ~/.gitconfig
ln -sfv "$DOTFILES/gitignore_global" ~/.gitignore_global
ln -sfv "$DOTFILES/vimrc" ~/.vimrc
ln -sfv "$DOTFILES/tmux.conf" ~/.tmux.conf
ln -sfv "$DOTFILES/.config/nvim/init.vim" ~/.config/nvim
ln -sfv "$DOTFILES/.config/nvim/coc-settings.json" ~/.config/nvim/coc-settings.json

if [ "$(uname -s)" = 'Darwin' ]; then

  [ -z "$(which brew)" ] &&
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  brew analytics off

  echo "=> Updating homebrew"

  brew install bat
  brew install cmake
  brew install coreutils
  brew install fd
  brew install fish
  brew install git
  brew install gh
  brew install htop
  brew install neovim
  brew install node
  brew install python@3.9
  brew install ripgrep
  brew install tmux
  brew install tree
  brew install vim

  brew install --cask alacritty
  brew install --cask visual-studio-code
  brew install --cask telegram
  brew install --cask rectangle

else
  echo "=> linux"
fi

echo "=> Install tmux tpm"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux source-file ~/.tmux.conf

echo "=> Install vim"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall

